CREATE TABLE Subjects(
SubjectID INT PRIMARY KEY IDENTITY,
SubjectName VARCHAR(50))

CREATE TABLE Majors(
MajorID INT PRIMARY KEY IDENTITY, 
[Name] VARCHAR(50))

CREATE TABLE Students(
StudentID INT PRIMARY KEY IDENTITY,
StudentNumber VARCHAR(50),
StudentName VARCHAR(50),
MajorID INT,
CONSTRAINT FK_Students_Majors FOREIGN KEY (MajorID) REFERENCES Majors (MajorID))

CREATE TABLE Payments(
PaymentID INT PRIMARY KEY IDENTITY,
PaymentDate DATETIME,
PaymentAmount DECIMAL(10,2),
StudentID INT,
CONSTRAINT FK_Payments_StudentID FOREIGN KEY (StudentID) REFERENCES Students (StudentID))

CREATE TABLE Agenda(
StudentID INT NOT NULL,
SubjectID INT NOT NULL,
CONSTRAINT PK_StudentID_SubjectID PRIMARY KEY (StudentID, SubjectID),
CONSTRAINT FK_Agenda_Students FOREIGN KEY (StudentID) REFERENCES Students (StudentID),
CONSTRAINT FK_Agenda_Subjects FOREIGN KEY (SubjectID) REFERENCES Subjects (SubjectID))
